import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/PageHeader";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCheck, Trash2 } from "lucide-react";
import { useLocation } from "wouter";
import { Empty } from "./Dashboard";

export default function Notifications() { const [, setLocation] = useLocation(); const list = trpc.notifications.list.useQuery({ page: 1, pageSize: 50, unreadOnly: false }); const utils = trpc.useUtils(); const mark = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() }); const all = trpc.notifications.markAllRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() }); const remove = trpc.notifications.remove.useMutation({ onSuccess: () => utils.notifications.list.invalidate() }); return <div><PageHeader title="Notifications" description="A real-time record of leave outcomes, workforce events, reports, and AI alerts."/><div className="rounded-2xl border border-slate-200 bg-card shadow-sm dark:border-white/10"><div className="flex items-center justify-between border-b p-4"><div className="flex items-center gap-2"><Bell className="h-4 w-4 text-indigo-600"/><p className="text-sm font-bold">Inbox</p>{(list.data?.unread ?? 0) > 0 && <span className="rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-semibold text-indigo-700">{list.data?.unread} unread</span>}</div><Button variant="outline" size="sm" className="rounded-lg" onClick={() => all.mutate()} disabled={!list.data?.unread || all.isPending}><CheckCheck className="mr-1.5 h-3.5 w-3.5"/>Mark all read</Button></div><div className="divide-y divide-slate-100 dark:divide-white/10">{list.isLoading ? <p className="p-8 text-center text-sm text-muted-foreground">Loading notifications…</p> : list.data?.items.length ? list.data.items.map(item => <div key={item.id} className={`flex gap-3 p-4 transition-colors ${!item.readAt ? "bg-indigo-50/45 dark:bg-indigo-500/5" : ""}`}><span className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-indigo-100 text-indigo-600 dark:bg-indigo-500/10"><Bell className="h-4 w-4"/></span><div className="min-w-0 flex-1"><button className="text-left" onClick={() => { if (!item.readAt) mark.mutate({ id: item.id }); if (item.href) setLocation(item.href); }}><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></button></div><div className="flex items-start gap-1"><Button variant="ghost" size="icon" onClick={() => mark.mutate({ id: item.id })} disabled={!!item.readAt} aria-label="Mark as read"><CheckCheck className="h-4 w-4"/></Button><Button variant="ghost" size="icon" className="text-muted-foreground hover:text-rose-600" onClick={() => remove.mutate({ id: item.id })} aria-label="Delete notification"><Trash2 className="h-4 w-4"/></Button></div></div>) : <div className="p-4"><Empty text="Your notification inbox is clear."/></div>}</div></div></div>; }

