import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/PageHeader";
import { useTheme } from "@/contexts/ThemeContext";
import { Moon, ShieldCheck, Sun } from "lucide-react";

export default function Settings() { const { user, logout } = useAuth(); const { theme, toggleTheme } = useTheme(); return <div><PageHeader title="Settings" description="Manage the account preferences and security context for your AttendAI session."/><div className="grid max-w-4xl gap-5"><section className="rounded-2xl border border-slate-200 bg-card p-6 shadow-sm dark:border-white/10"><p className="text-sm font-bold">Profile</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Name" value={user?.name ?? "Not available"}/><Info label="Email" value={user?.email ?? "Not available"}/><Info label="Access role" value={<Badge className="bg-indigo-100 text-indigo-700 hover:bg-indigo-100">{user?.role === "hr_manager" ? "HR Manager" : user?.role}</Badge>}/><Info label="Authentication" value="Secure OAuth session"/></div></section><section className="rounded-2xl border border-slate-200 bg-card p-6 shadow-sm dark:border-white/10"><p className="text-sm font-bold">Appearance</p><p className="mt-1 text-sm text-muted-foreground">Your selected theme is stored in this browser.</p><Button variant="outline" className="mt-4 rounded-xl" onClick={toggleTheme}>{theme === "dark" ? <Sun className="mr-2 h-4 w-4"/> : <Moon className="mr-2 h-4 w-4"/>}Switch to {theme === "dark" ? "light" : "dark"} mode</Button></section><section className="rounded-2xl border border-slate-200 bg-card p-6 shadow-sm dark:border-white/10"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-4 w-4 text-emerald-600"/>Session security</div><p className="mt-2 text-sm text-muted-foreground">Your authentication session is protected by the platform. Signing out clears the active session from this browser.</p></div><Button variant="outline" className="shrink-0 rounded-xl" onClick={logout}>Sign out</Button></div></section></div></div>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><div className="mt-1 text-sm font-medium">{value}</div></div>; }

